// <auto-generated />
using System;
using FiveThreeOneTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiveThreeOneTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412214558_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("FiveThreeOneTracker.Models.Accessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accessories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bent-over barbell row",
                            IsActive = true,
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Single-arm dumbbell row",
                            IsActive = true,
                            Name = "Dumbbell Row"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cable lat pulldown",
                            IsActive = true,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cable face pull",
                            IsActive = true,
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Parallel bar dips",
                            IsActive = true,
                            Name = "Dips"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Chin-ups / pull-ups",
                            IsActive = true,
                            Name = "Chin-Ups"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lying or seated leg curl",
                            IsActive = true,
                            Name = "Leg Curl"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Machine leg press",
                            IsActive = true,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ab wheel rollout",
                            IsActive = true,
                            Name = "Ab Wheel"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Hanging leg raise",
                            IsActive = true,
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Standing dumbbell curl",
                            IsActive = true,
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Cable tricep pushdown",
                            IsActive = true,
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Dumbbell lateral raise",
                            IsActive = true,
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Romanian deadlift",
                            IsActive = true,
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Rear foot elevated split squat",
                            IsActive = true,
                            Name = "Bulgarian Split Squat"
                        });
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.AccessoryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.ToTable("AccessoryHistory");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Cycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Lift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BbbPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("LiftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("TrainingMax")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LiftType")
                        .IsUnique();

                    b.ToTable("Lifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BbbPercentage = 50.0,
                            LiftType = "Squat",
                            Name = "Squat",
                            TrainingMax = 315.0
                        },
                        new
                        {
                            Id = 2,
                            BbbPercentage = 50.0,
                            LiftType = "BenchPress",
                            Name = "Bench Press",
                            TrainingMax = 225.0
                        },
                        new
                        {
                            Id = 3,
                            BbbPercentage = 50.0,
                            LiftType = "Deadlift",
                            Name = "Deadlift",
                            TrainingMax = 365.0
                        },
                        new
                        {
                            Id = 4,
                            BbbPercentage = 50.0,
                            LiftType = "OverheadPress",
                            Name = "Overhead Press",
                            TrainingMax = 145.0
                        });
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Week", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainLiftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.WorkoutAccessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutAccessories");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualReps")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActualWeight")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrescribedReps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrescribedWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LiftId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.AccessoryHistory", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.Accessory", "Accessory")
                        .WithMany("History")
                        .HasForeignKey("AccessoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessory");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Week", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.Cycle", "Cycle")
                        .WithMany("Weeks")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Workout", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.Week", "Week")
                        .WithMany("Workouts")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.WorkoutAccessory", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.Accessory", "Accessory")
                        .WithMany("WorkoutAccessories")
                        .HasForeignKey("AccessoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiveThreeOneTracker.Models.Workout", "Workout")
                        .WithMany("WorkoutAccessories")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessory");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.WorkoutSet", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.Lift", "Lift")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("LiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiveThreeOneTracker.Models.Workout", "Workout")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lift");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Accessory", b =>
                {
                    b.Navigation("History");

                    b.Navigation("WorkoutAccessories");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Cycle", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Lift", b =>
                {
                    b.Navigation("WorkoutSets");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Week", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Workout", b =>
                {
                    b.Navigation("Sets");

                    b.Navigation("WorkoutAccessories");
                });
#pragma warning restore 612, 618
        }
    }
}
