// <auto-generated />
using System;
using FiveThreeOneTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiveThreeOneTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiveThreeOneTracker.Models.Accessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Accessories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bent-over barbell row",
                            IsActive = true,
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Single-arm dumbbell row",
                            IsActive = true,
                            Name = "Dumbbell Row"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cable lat pulldown",
                            IsActive = true,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cable face pull",
                            IsActive = true,
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Parallel bar dips",
                            IsActive = true,
                            Name = "Dips"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Chin-ups / pull-ups",
                            IsActive = true,
                            Name = "Chin-Ups"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lying or seated leg curl",
                            IsActive = true,
                            Name = "Leg Curl"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Machine leg press",
                            IsActive = true,
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ab wheel rollout",
                            IsActive = true,
                            Name = "Ab Wheel"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Hanging leg raise",
                            IsActive = true,
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Standing dumbbell curl",
                            IsActive = true,
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Cable tricep pushdown",
                            IsActive = true,
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Dumbbell lateral raise",
                            IsActive = true,
                            Name = "Lateral Raise"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Romanian deadlift",
                            IsActive = true,
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Rear foot elevated split squat",
                            IsActive = true,
                            Name = "Bulgarian Split Squat"
                        });
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.AccessoryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.ToTable("AccessoryHistory");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Cycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BbbMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("BbbPercentage")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IncludeFsl")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeWarmup")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFivesPro")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Lift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BbbPercentage")
                        .HasColumnType("double precision");

                    b.Property<string>("LiftType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("TrainingMax")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LiftType")
                        .IsUnique();

                    b.ToTable("Lifts");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PlateInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PairsAvailable")
                        .HasColumnType("integer");

                    b.Property<int>("UserEquipmentId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserEquipmentId");

                    b.ToTable("PlateInventory");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplDayTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderInWeek")
                        .HasColumnType("integer");

                    b.Property<int>("PplProgramId")
                        .HasColumnType("integer");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PplProgramId");

                    b.ToTable("PplDayTemplates");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplExerciseSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CurrentWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBodyweight")
                        .HasColumnType("boolean");

                    b.Property<int?>("LiftId")
                        .HasColumnType("integer");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderInDay")
                        .HasColumnType("integer");

                    b.Property<int>("PplDayTemplateId")
                        .HasColumnType("integer");

                    b.Property<double>("ProgressionIncrement")
                        .HasColumnType("double precision");

                    b.Property<int>("RepsMax")
                        .HasColumnType("integer");

                    b.Property<int>("RepsMin")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer");

                    b.Property<double>("TmPercentage")
                        .HasColumnType("double precision");

                    b.Property<bool>("UsePercentageOfTm")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("LiftId");

                    b.HasIndex("PplDayTemplateId");

                    b.ToTable("PplExerciseSlots");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PplPrograms");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PplDayTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("PplProgramId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PplDayTemplateId");

                    b.HasIndex("PplProgramId");

                    b.ToTable("PplSessions");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplSessionExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderInSession")
                        .HasColumnType("integer");

                    b.Property<int>("PplExerciseSlotId")
                        .HasColumnType("integer");

                    b.Property<int>("PplSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("RepsMax")
                        .HasColumnType("integer");

                    b.Property<int>("RepsMin")
                        .HasColumnType("integer");

                    b.Property<double>("SuggestedWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PplExerciseSlotId");

                    b.HasIndex("PplSessionId");

                    b.ToTable("PplSessionExercises");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplSessionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualReps")
                        .HasColumnType("integer");

                    b.Property<double?>("ActualWeight")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PplSessionExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TargetReps")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PplSessionExerciseId");

                    b.ToTable("PplSessionSets");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.UserEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BarWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserEquipment");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Week", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CycleId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MainLiftType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.WorkoutAccessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutAccessories");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualReps")
                        .HasColumnType("integer");

                    b.Property<double?>("ActualWeight")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LiftId")
                        .HasColumnType("integer");

                    b.Property<int>("PrescribedReps")
                        .HasColumnType("integer");

                    b.Property<double>("PrescribedWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LiftId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.AccessoryHistory", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.Accessory", "Accessory")
                        .WithMany("History")
                        .HasForeignKey("AccessoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessory");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PlateInventory", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.UserEquipment", "UserEquipment")
                        .WithMany("Plates")
                        .HasForeignKey("UserEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEquipment");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplDayTemplate", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.PplProgram", "Program")
                        .WithMany("DayTemplates")
                        .HasForeignKey("PplProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplExerciseSlot", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.Lift", "Lift")
                        .WithMany()
                        .HasForeignKey("LiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FiveThreeOneTracker.Models.PplDayTemplate", "DayTemplate")
                        .WithMany("ExerciseSlots")
                        .HasForeignKey("PplDayTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayTemplate");

                    b.Navigation("Lift");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplSession", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.PplDayTemplate", "DayTemplate")
                        .WithMany("Sessions")
                        .HasForeignKey("PplDayTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FiveThreeOneTracker.Models.PplProgram", "Program")
                        .WithMany("Sessions")
                        .HasForeignKey("PplProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayTemplate");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplSessionExercise", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.PplExerciseSlot", "ExerciseSlot")
                        .WithMany("SessionExercises")
                        .HasForeignKey("PplExerciseSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FiveThreeOneTracker.Models.PplSession", "Session")
                        .WithMany("Exercises")
                        .HasForeignKey("PplSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseSlot");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplSessionSet", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.PplSessionExercise", "SessionExercise")
                        .WithMany("Sets")
                        .HasForeignKey("PplSessionExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionExercise");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Week", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.Cycle", "Cycle")
                        .WithMany("Weeks")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Workout", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.Week", "Week")
                        .WithMany("Workouts")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.WorkoutAccessory", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.Accessory", "Accessory")
                        .WithMany("WorkoutAccessories")
                        .HasForeignKey("AccessoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiveThreeOneTracker.Models.Workout", "Workout")
                        .WithMany("WorkoutAccessories")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessory");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.WorkoutSet", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.Lift", "Lift")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("LiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiveThreeOneTracker.Models.Workout", "Workout")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lift");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiveThreeOneTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FiveThreeOneTracker.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Accessory", b =>
                {
                    b.Navigation("History");

                    b.Navigation("WorkoutAccessories");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Cycle", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Lift", b =>
                {
                    b.Navigation("WorkoutSets");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplDayTemplate", b =>
                {
                    b.Navigation("ExerciseSlots");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplExerciseSlot", b =>
                {
                    b.Navigation("SessionExercises");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplProgram", b =>
                {
                    b.Navigation("DayTemplates");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplSession", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.PplSessionExercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.UserEquipment", b =>
                {
                    b.Navigation("Plates");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Week", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("FiveThreeOneTracker.Models.Workout", b =>
                {
                    b.Navigation("Sets");

                    b.Navigation("WorkoutAccessories");
                });
#pragma warning restore 612, 618
        }
    }
}
